### DISCUSSION TITLE
post/2021/2021-06-giscus/

### DISCUSSION THREAD

**Discussion by giscus** [zyrikby/website_related#18] [Announcements]
# post/2021/2021-06-giscus/

This tutorial describes how to wheel your Wowchemy-based website to a new commenting engine called giscus.

https://zhauniarovich.com/post/2021/2021-06-giscus/

**Comment by Karobben** [comment]
Thanks man, but do you know where can I find my `data-repo-id` and `data-category-id`?

**Reply by Karobben** [reply]
Thanks man, I fixed it by myself. It is a good document!

**Reply by bloggrammer** [reply]
How can I find mi `data-repo-id` and `data-category-id`?

**Reply by zyrikby** [reply]
@Blogrammer you should go to the https://giscus.app/ and provide the details about your repository used for commenting. This is described in [this section](https://zhauniarovich.com/post/2021/2021-06-giscus/#configuring-giscus-parameters)

**Reply by bloggrammer** [reply]
Thanks for your quick reply, @zyrikby it works as expected

**Comment by jpmorr** [comment]
Nice instructions. My preference was to use commento but I just can't self-host the free version, it's too difficult when you don't have access to a server to run it on and it's too expensive for a few comments a year.  I spent a lot of time thinking about this and other GitHub based comment systems such as utteranc.es but eventually ruled them out as the people most likely to comment probably aren't GitHub user, so I look at Talkyard as it's cheap, but was a bit difficult to implement. In the end I've ended up with disqus while I rethink what to do. I may be coming back to this guide if I change my mind.

**Reply by zyrikby** [reply]
The audience of my blog is mainly technical, so I assume that they have a Github account. However, if you write to a more generic audience then you're right, it's worth to investigate other options.

**Comment by weitse-hsu** [comment]
Thanks a lot for writing this article! It's crystal clear! The only thing is that wowchemy has changed `params.toml` into `params.yaml` and its variables. In the newer version, the `comment` section is under `features`. For those who are interested, I made the following changes to have giscus work in my case:
- Use `giscus.html` with the following content:
  ```
  {{ if site.Params.features.comment.giscus }}
  <script src="https://giscus.app/client.js"
          data-repo="{{site.Params.features.comment.giscus.repo}}"
          data-repo-id="{{site.Params.features.comment.giscus.repo_id}}"
          data-category="{{site.Params.features.comment.giscus.category}}"
          data-category-id="{{site.Params.features.comment.giscus.category_id}}"
          data-mapping="{{site.Params.features.comment.giscus.mapping}}"
          data-reactions-enabled="{{site.Params.features.comment.giscus.reactions_enabled}}"
          data-theme="{{site.Params.features.comment.giscus.theme}}"
          crossorigin="anonymous"
          async>
  </script>
  <noscript>Please enable JavaScript to view the comments powered by giscus.</noscript>
  {{ end }}
  ```
- Modify `params.yaml`. For example, the whole `features` section (which includes the `comment` section) looks like below:
  ```
  # Site features
  features:
    syntax_highlighter:
      enable: true
      extra_languages:
        - r
        - latex
    math:
      enable: true
    privacy_pack:
      enable: false
    repository:
      url: 'https://github.com/<username>/<repository>'
      content_dir: content
      branch: master
    avatar:
      gravatar: false
      shape: circle
    comment:
       provider: 'giscus'
      disqus:
        shortname: ''
        show_count: 
      commento:
        url: 
      giscus:
        repo: "<data-repo>"  # Repo where the comments will live
        repo_id: "<data-repo-id>"
        category: "Announcements"
        category_id: "<data-category-id>"
        mapping: "pathname"  # How Utterances will match comment to page
        label: "comment"     # Label applied to issue by utteranc.es bot
        theme: "dark"        # What theme to use
        reactions_enabled: "1"
    search:
      provider: wowchemy
      algolia:
        app_id: ''
        api_key: ''
        index_name: ''
        show_logo: false
    map:
      provider: ''
      api_key: ''
      zoom: 15
  ```
